name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Ephie
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transport-layer
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Ephie-client
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
