name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Nav
      run: cd Ephie
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Nav
      run: cd transport-layer
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Nav
      run: cd Ephie-client
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
